export const AVAILABLE_CURRENCIES = {
  'btc': 'bitcoin',
  'eth': 'ethereum',
  'pax': 'paxos',
  'xrp': 'ripple',
  'eos': 'eos',
  'bch': 'bch',
  'trx': 'TRON',
  'bnb': 'BNBERC20',
  'bnbmainnet': 'BNBMAINNET',
  'fun': 'FunFactory',
  'xvg': 'Verge',
  'zen': 'Horizen',
  'dgb': 'DigiByte',
  'dgd': 'DigixDAO',
  'xmr': 'Monero',
  'ltc': 'Litecoin',
  'ht': 'HT',
  'qtum': 'QTUM',
  'usdt': 'USDT',
  'usdterc20': 'USDTERC20',
  'dcr': 'Decred',
  'bcd': 'Bitcoin Diamond',
  'dash': 'Dash',
  'ont': 'ONT',
  'tusd': 'TrueUSD',
  'gas': 'GAS',
  'neo': 'NEO',
  'ada': 'Kardano',
  'waves': 'Waves',
  'xlm': 'Stellar',
  'btg': 'Bitcoin Gold',
  'grs': 'Groestlcoin',
  'xzc': 'Zcoin',
  'zec': 'Zcash',
};
